'@context': null
ontologies:
  - id: ncit
    preferredPrefix: NCIT
    title: NCI Thesaurus OBO Edition
    description: >
      NCI Thesaurus (NCIt)is a reference terminology that includes broad coverage of the cancer domain, including cancer related diseases, findings and abnormalities. The NCIt OBO Edition aims to increase integration of the NCIt with OBO Library ontologies.
    uri: http://purl.obolibrary.org/obo/ncit/ncit.owl
    base_uri:
      - http://purl.obolibrary.org/obo/NCIT_
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    reasoner: EL
    oboSlims: false
    ontology_purl: http://purl.obolibrary.org/obo/ncit/ncit.owl
    allow_download: false
  - id: ncit_plus
    preferredPrefix: NCIT
    title: NCI Thesaurus Plus
    description: >
      The NCIt Plus replaces some NCIt terms with direct references to terms from other domain-specific OBO Library ontologies (e.g. cell types, cellular components, anatomy). The current release incorporates CL (cell types) and Uberon (anatomy).
    uri: http://purl.obolibrary.org/obo/ncit/ncit-plus.owl
    base_uri:
      - http://purl.obolibrary.org/obo/NCIT_
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    reasoner: EL
    oboSlims: false
    ontology_purl: http://purl.obolibrary.org/obo/ncit/ncit-plus.owl
    allow_download: false
